name: Build and Push Docker Image

on:
  # Uncomment the following lines if you want to trigger the workflow on a push event
  # push:
  #   branches:
  #     - main  # Change this to your desired branch
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Docker image tag'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry (ACR)
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker Image
        run: docker build -f Dockerfile.linux -t ${{ vars.ACR_NAME }}:${{ github.event.inputs.image-tag }} .

      - name: Push Docker Image
        run: docker push ${{ vars.ACR_NAME }}:${{ github.event.inputs.image-tag }}
